version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db_inits:/docker-entrypoint-initdb.d/:ro
      - ${DB_PATH}:/var/lib/mysql
    env_file:
      - .env

  web_app:
    depends_on:
      - db
    container_name: home_drive_web_app
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${STORAGE_FILES_PATH}:/HomeDrive/storage/files
      - ${STORAGE_PRIVATE_PATH}:/HomeDrive/storage/private
      - ${STORAGE_TMP_PATH}:/HomeDrive/storage/tmp
    env_file:
      - .env
