version: "3"
services:
  redis:
    web_app:
      container_name: home_drive_web_app
      build: .
      restart: unless-stopped
      ports:
        - "8080:8080"
      volumes:
        - ${STORAGE_FILES_PATH}:/HomeDrive/storage/files
        - ${STORAGE_PRIVATE_PATH}:/HomeDrive/storage/private
        - ${STORAGE_TMP_PATH}:/HomeDrive/storage/tmp
        - ${DB_PATH}:/HomeDrive/database
      env_file:
        - .env
